//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edelweiss.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edelweiss.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;background-color: #f5f5f5;font-family:sans-serif;&quot;&gt;
        ///    &lt;div id=&quot;container&quot; style=&quot;max-width:600px; margin:auto; border: 1px solid #dfdfdf;&quot;&gt;
        ///        &lt;div id=&quot;header&quot; style=&quot;background-color:#dc3545;&quot;&gt;
        ///            &lt;h3 style=&quot;color:#ffffff; text-align:center; padding-top:10px; padding-bottom:10px; margin:0px;&quot;&gt;{{subject}}&lt;/h3&gt;
        ///        &lt;/div&gt;
        ///        &lt;div id=&quot;body&quot; style=&quot;background-color:#ffe6e6; padding:10px;&quot;&gt;
        ///            &lt;p&gt;Uma exceção foi disparada &lt;/p&gt;
        ///            &lt;table style=&quot;borde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string error_notification {
            get {
                return ResourceManager.GetString("error_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;background-color: #f5f5f5;font-family:sans-serif;&quot;&gt;
        ///    &lt;div id=&quot;container&quot; style=&quot;max-width:600px; margin:auto; border: 1px solid #dfdfdf;&quot;&gt;
        ///        &lt;div id=&quot;header&quot; style=&quot;background-color:#154572;&quot;&gt;
        ///            &lt;h3 style=&quot;color:#ffffff; text-align:center; padding-top:10px; padding-bottom:10px; margin:0px;&quot;&gt;{{subject}}&lt;/h3&gt;
        ///        &lt;/div&gt;
        ///        &lt;div id=&quot;body&quot; style=&quot;background-color:#ffffff; padding:10px;&quot;&gt;
        ///            {{message-body}}
        ///            &lt;div style=&quot;border-width:1px; border [rest of string was truncated]&quot;;.
        /// </summary>
        public static string information_notification {
            get {
                return ResourceManager.GetString("information_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;background-color: #f5f5f5;font-family:sans-serif;&quot;&gt;
        ///    &lt;div id=&quot;container&quot; style=&quot;max-width:600px; margin:auto; border: 1px solid #dfdfdf;&quot;&gt;
        ///        &lt;div id=&quot;header&quot; style=&quot;background-color:#28a745;&quot;&gt;
        ///            &lt;h3 style=&quot;color:#ffffff; text-align:center; padding-top:10px; padding-bottom:10px; margin:0px;&quot;&gt;{{subject}}&lt;/h3&gt;
        ///        &lt;/div&gt;
        ///        &lt;div id=&quot;body&quot; style=&quot;background-color:#ffffff; padding:10px;&quot;&gt;
        ///            {{message-body}}
        ///            &lt;div style=&quot;border-width:1px; border [rest of string was truncated]&quot;;.
        /// </summary>
        public static string success_notification {
            get {
                return ResourceManager.GetString("success_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;background-color: #f5f5f5;font-family:sans-serif;&quot;&gt;
        ///    &lt;div id=&quot;container&quot; style=&quot;max-width:600px; margin:auto; border: 1px solid #dfdfdf;&quot;&gt;
        ///        &lt;div id=&quot;header&quot; style=&quot;background-color:#ffc107;&quot;&gt;
        ///            &lt;h3 style=&quot;color:#ffffff; text-align:center; padding-top:10px; padding-bottom:10px; margin:0px;&quot;&gt;{{subject}}&lt;/h3&gt;
        ///        &lt;/div&gt;
        ///        &lt;div id=&quot;body&quot; style=&quot;background-color:#ffffff; padding:10px;&quot;&gt;
        ///            {{message-body}}
        ///            &lt;div style=&quot;border-width:1px; border [rest of string was truncated]&quot;;.
        /// </summary>
        public static string warning_notification {
            get {
                return ResourceManager.GetString("warning_notification", resourceCulture);
            }
        }
    }
}
